import { NextResponse } from "next/server";

const DEMO_DATA = {
  overview: {
    username: "demo_user",
    realname: "Music Lover",
    avatar: "",
    totalScrobbles: 84732,
    periodScrobbles: 4821,
    estimatedHoursListened: 312.5,
    daysActive: 156,
    averagePerDay: 30.9,
    periodLabel: "January \u2013 June 2025",
    tracksWithoutDuration: 234,
  },
  topArtists: [
    { name: "Radiohead", playcount: 342, rank: 1, image: "", mbid: "", percentage: 7 },
    { name: "Arcade Fire", playcount: 289, rank: 2, image: "", mbid: "", percentage: 6 },
    { name: "Tame Impala", playcount: 267, rank: 3, image: "", mbid: "", percentage: 5.5 },
    { name: "The National", playcount: 234, rank: 4, image: "", mbid: "", percentage: 4.9 },
    { name: "Bon Iver", playcount: 198, rank: 5, image: "", mbid: "", percentage: 4.1 },
    { name: "Sufjan Stevens", playcount: 187, rank: 6, image: "", mbid: "", percentage: 3.9 },
    { name: "Khruangbin", playcount: 176, rank: 7, image: "", mbid: "", percentage: 3.7 },
    { name: "MF DOOM", playcount: 164, rank: 8, image: "", mbid: "", percentage: 3.4 },
  ],
  topAlbums: [
    { name: "OK Computer", artist: "Radiohead", playcount: 156, rank: 1, image: "", mbid: "" },
    { name: "Funeral", artist: "Arcade Fire", playcount: 134, rank: 2, image: "", mbid: "" },
    { name: "Currents", artist: "Tame Impala", playcount: 129, rank: 3, image: "", mbid: "" },
    { name: "Boxer", artist: "The National", playcount: 118, rank: 4, image: "", mbid: "" },
    { name: "For Emma, Forever Ago", artist: "Bon Iver", playcount: 112, rank: 5, image: "", mbid: "" },
    { name: "Illinois", artist: "Sufjan Stevens", playcount: 98, rank: 6, image: "", mbid: "" },
  ],
  topTags: [
    { name: "indie rock", count: 892, rank: 1 },
    { name: "alternative", count: 756, rank: 2 },
    { name: "indie", count: 623, rank: 3 },
    { name: "alt rock", count: 534, rank: 4 },
    { name: "rock", count: 489, rank: 5 },
    { name: "experimental", count: 412, rank: 6 },
    { name: "electronic", count: 378, rank: 7 },
    { name: "psychedelic", count: 345, rank: 8 },
    { name: "art rock", count: 298, rank: 9 },
    { name: "lo-fi", count: 267, rank: 10 },
    { name: "hip-hop", count: 234, rank: 11 },
    { name: "dream pop", count: 198, rank: 12 },
  ],
  topTracks: [
    { name: "Paranoid Android", artist: "Radiohead", playcount: 67, rank: 1, image: "", duration: 386, mbid: "" },
    { name: "Wake Up", artist: "Arcade Fire", playcount: 59, rank: 2, image: "", duration: 345, mbid: "" },
    { name: "Let It Happen", artist: "Tame Impala", playcount: 54, rank: 3, image: "", duration: 467, mbid: "" },
    { name: "Fake Empire", artist: "The National", playcount: 48, rank: 4, image: "", duration: 232, mbid: "" },
    { name: "Skinny Love", artist: "Bon Iver", playcount: 45, rank: 5, image: "", duration: 234, mbid: "" },
    { name: "Chicago", artist: "Sufjan Stevens", playcount: 41, rank: 6, image: "", duration: 360, mbid: "" },
    { name: "People Everywhere", artist: "Khruangbin", playcount: 38, rank: 7, image: "", duration: 274, mbid: "" },
    { name: "Doomsday", artist: "MF DOOM", playcount: 36, rank: 8, image: "", duration: 262, mbid: "" },
  ],
  listeningPatterns: {
    hourlyDistribution: [12,5,3,2,1,2,8,34,89,156,198,210,234,256,278,289,267,245,223,198,167,134,89,45],
    dayOfWeekDistribution: [654,689,712,698,734,623,611],
    monthlyDistribution: [
      { month: "Jan 25", count: 723 },
      { month: "Feb 25", count: 812 },
      { month: "Mar 25", count: 789 },
      { month: "Apr 25", count: 867 },
      { month: "May 25", count: 934 },
      { month: "Jun 25", count: 696 },
    ],
    peakHour: 15,
    peakDay: "Fri",
    longestStreak: 23,
    busiestDay: { date: "2025-03-15", count: 87 },
  },
  diversity: { uniqueArtists: 423, uniqueAlbums: 612, uniqueTracks: 1892, genreCount: 12 },
  funFacts: {
    firstTrack: { name: "Everything In Its Right Place", artist: "Radiohead", date: "01 Jan 2025, 00:12" },
    lastTrack: { name: "Midnight City", artist: "M83", date: "30 Jun 2025, 23:45" },
    longestTrack: { name: "Let It Happen", artist: "Tame Impala", duration: 467 },
    shortestTrack: { name: "Intermission", artist: "Blur", duration: 72 },
    averageTrackDuration: 234,
    mostProductiveHour: 15,
    midnightListener: true,
    weekendWarrior: false,
  },
};

export async function GET() {
  return NextResponse.json(DEMO_DATA);
}
